-- Create the Hesudhar dictionary table
CREATE TABLE IF NOT EXISTS hesudhar_dictionary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word TEXT NOT NULL UNIQUE,
    correct TEXT NOT NULL,
    is_flagged BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE hesudhar_dictionary ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read access" ON hesudhar_dictionary
    FOR SELECT USING (true);

CREATE POLICY "Allow authenticated full access" ON hesudhar_dictionary
    FOR ALL USING (auth.role() = 'authenticated');
